apiVersion: "stable.agones.dev/v1alpha1"
kind: GameServer
metadata:
  name: "holox-server2"
spec:
  portPolicy: "dynamic"
  containerPort: 7777
  template:
    spec:
      containers:
      - name: holox-server2
        image: wassx/holoxserver:1.0.6
